"""empty message

Revision ID: 16a943e00203
Revises: f922b1bd343b
Create Date: 2019-10-09 23:11:52.670344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a943e00203'
down_revision = 'f922b1bd343b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_goals_project_id'), 'goals', ['project_id'], unique=False)
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_index('ix_project_department', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_department', 'project', ['department'], unique=False)
    op.create_foreign_key(None, 'goals', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_goals_project_id'), table_name='goals')
    # ### end Alembic commands ###
