"""empty message

Revision ID: 9eced8f220b1
Revises: da3ba52a5976
Create Date: 2019-11-18 14:56:15.657299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eced8f220b1'
down_revision = 'da3ba52a5976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('member', sa.String(length=64), nullable=True))
    op.add_column('members', sa.Column('project', sa.String(length=64), nullable=True))
    op.drop_column('members', 'project_id')
    op.drop_column('members', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('members', 'project')
    op.drop_column('members', 'member')
    # ### end Alembic commands ###
