"""empty message

Revision ID: a3595b02d47e
Revises: c0508004cbf6
Create Date: 2019-11-22 20:13:57.371328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3595b02d47e'
down_revision = 'c0508004cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'goals', 'project', ['project_id'], ['projectname'])
    op.create_foreign_key(None, 'members', 'user', ['member'], ['username'])
    op.create_foreign_key(None, 'members', 'project', ['project'], ['projectname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    # ### end Alembic commands ###
