"""empty message

Revision ID: a4d2792327a0
Revises: 4760e1f94308
Create Date: 2019-10-10 00:06:03.082716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d2792327a0'
down_revision = '4760e1f94308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goals_goal', table_name='goals')
    op.drop_index('ix_goals_project_id', table_name='goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_goals_project_id', 'goals', ['project_id'], unique=False)
    op.create_index('ix_goals_goal', 'goals', ['goal'], unique=False)
    # ### end Alembic commands ###
