"""empty message

Revision ID: c0508004cbf6
Revises: 57fbc5f03b32
Create Date: 2019-11-18 21:21:44.493371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0508004cbf6'
down_revision = '57fbc5f03b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_goals_project_id'), 'goals', ['project_id'], unique=True)
    op.drop_column('goals', 'goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('goal', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_goals_project_id'), table_name='goals')
    # ### end Alembic commands ###
