"""empty message

Revision ID: da3ba52a5976
Revises: c5419613babf
Create Date: 2019-11-06 15:51:18.747228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3ba52a5976'
down_revision = 'c5419613babf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_members_member_id', table_name='members')
    op.drop_index('ix_members_project_id', table_name='members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_members_project_id', 'members', ['project_id'], unique=False)
    op.create_index('ix_members_member_id', 'members', ['member_id'], unique=False)
    # ### end Alembic commands ###
